name:                pcap-replicator
version:             0.1.0.0
github:              "demaledetti/pcap-replicator"
license:             BSD3
author:              "Stefano Debenedetti"
maintainer:          "44903077+demaledetti@users.noreply.github.com"
copyright:           "2022 Stefano Debenedetti"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/demaledetti/pcap-replicator#readme>

language: GHC2021

dependencies:
- attoparsec
- base >= 4.7 && < 5
- binary
- bytestring
- contra-tracer
- exceptions
- fusion-plugin
- hw-ip
- mtl
- network
- network-simple
- optparse-applicative
- process
- say
- streaming
- streaming-attoparsec
- streaming-bytestring
- streamly
- streamly-bytestring
- streamly-process
- text

ghc-options:
- -Wall
# https://streamly.composewell.com/streamly-0.8.2/Compiling.html#compilation-options
- -fdicts-strict
- -fmax-worker-args=16
- -fspec-constr-recursive=16
- -fplugin Fusion.Plugin

library:
  source-dirs: src

executables:
  pcap-replicator-ioref:
    main:                Main.hs
    source-dirs:         app-ioref
    dependencies:
    - pcap-replicator
    ghc-options:
    - -threaded
    - -rtsopts
    #- -with-rtsopts=-N2
  pcap-replicator-statet:
    main:                Main.hs
    source-dirs:         app-statet
    dependencies:
    - pcap-replicator
    ghc-options:
    - -threaded
    - -rtsopts

benchmarks:
  pcap-replicator:
    main:                Main.hs
    source-dirs:         bench
    dependencies:
    - pcap-replicator
    - tasty
    - tasty-bench
    ghc-options:
    - -threaded
    - -rtsopts

