name:                pcap-replicator
version:             0.1.0.0
github:              "demaledetti/pcap-replicator"
license:             BSD3
author:              "Stefano Debenedetti"
maintainer:          "44903077+demaledetti@users.noreply.github.com"
copyright:           "2022 Stefano Debenedetti"

extra-source-files:
- README.md
- cabal*project*

description:         Please see the README on GitHub at <https://github.com/demaledetti/pcap-replicator#readme>

language: GHC2021

tested-with:
- GHC == 9.8.4
- GHC == 9.10.1
- GHC == 9.12.2

dependencies:
- base >= 4.7 && < 5
- fusion-plugin

ghc-options:
- -Wall
- -Wunused-packages
# https://streamly.composewell.com/streamly-0.8.2/Compiling.html#compilation-options
- -fdicts-strict
- -fmax-worker-args=16
- -fspec-constr-recursive=16
- -fplugin Fusion.Plugin
# core
- -ddump-simpl
- -ddump-opt-cmm
# - -dsuppress-all
- -dsuppress-uniques
- -ddump-to-file
# stan
- -fwrite-ide-info
- -hiedir=.hie
# workaround for GHC issue #24507
# not needed for 9.12.x
#                9.10.2+
#                9.8.3+
# - -fno-asm-shortcutting

library:
  source-dirs: src
  dependencies:
  - attoparsec
  - binary
  - bytestring
  - contra-tracer
  - data-textual
  - exceptions
  - mtl
  - network
  - network-ip
  - network-simple
  - optparse-applicative >= 0.19
  - process
  - say
  - streaming
  - streaming-attoparsec
  - streaming-bytestring
  - streamly
  - streamly-bytestring >= 0.2.1
  - streamly-core
  # - streamly-process
  - text

executables:
  pcap-replicator:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - pcap-replicator
    ghc-options:
    - -threaded
    - -rtsopts
    #- -with-rtsopts=-N2

benchmarks:
  pcap-replicator-bench:
    main:                Main.hs
    source-dirs:         bench
    dependencies:
    - bytestring
    - filepath
    - pcap-replicator
    - process
    - streamly
    - streamly-core
    - tasty
    - tasty-bench
    build-tools:
    - pcap-replicator:pcap-replicator
    - pcap-replicator:pcap-replicator
    ghc-options:
    - -threaded
    - -rtsopts
