name:                pcap-replicator
version:             0.1.0.0
github:              "demaledetti/pcap-replicator"
license:             BSD3
author:              "Stefano Debenedetti"
maintainer:          "44903077+demaledetti@users.noreply.github.com"
copyright:           "2022 Stefano Debenedetti"

extra-source-files:
- README.md
- cabal*project*

description:         Please see the README on GitHub at <https://github.com/demaledetti/pcap-replicator#readme>

language: GHC2021

dependencies:
- base >= 4.7 && < 5
- fusion-plugin
- streamly
- streamly-core

ghc-options:
- -Wall
- -Wunused-packages
# https://streamly.composewell.com/streamly-0.8.2/Compiling.html#compilation-options
- -fdicts-strict
- -fmax-worker-args=16
- -fspec-constr-recursive=16
- -fplugin Fusion.Plugin
# core
- -ddump-simpl
- -ddump-opt-cmm
# - -dsuppress-all
- -dsuppress-uniques
- -ddump-to-file
# stan
- -fwrite-ide-info
- -hiedir=.hie

library:
  source-dirs: src
  dependencies:
  - attoparsec
  - bytestring
  - contra-tracer
  - exceptions
  - hw-ip
  - network
  - network-simple
  - optparse-applicative
  - process
  - say
  - streaming
  - streaming-attoparsec
  - streaming-bytestring
  - streamly-bytestring
  # - streamly-process
  - text

executables:
  pcap-replicator-ioref:
    main:                Main.hs
    source-dirs:         app-ioref
    dependencies:
    - pcap-replicator
    ghc-options:
    - -threaded
    - -rtsopts
    #- -with-rtsopts=-N2
  pcap-replicator-statet:
    main:                Main.hs
    source-dirs:         app-statet
    dependencies:
    - contra-tracer
    - exceptions
    - pcap-replicator
    - mtl
    - network
    ghc-options:
    - -threaded
    - -rtsopts

benchmarks:
  pcap-replicator:
    main:                Main.hs
    source-dirs:         bench
    dependencies:
    - bytestring
    - pcap-replicator
    - process
    - tasty
    - tasty-bench
    build-tool-depends:
    - pcap-replicator:pcap-replicator-ioref
    - pcap-replicator:pcap-replicator-statet
    ghc-options:
    - -threaded
    - -rtsopts

